### ISSUE TITLE
Is this project still being updated?

### ISSUE THREAD

**Issue by eirikh1996** [nixxholas/EasyElevator#1]
I was curious about one thing: Is this project ever being updated or not?

**Comment by nixxholas** [comment]
I have never expected anyone to use this.

I will maintain this repo if there are issues being posted with regards to version compatibility.

There is no point fixing the glitches of this plugin, its horrendously coded

**Comment by eirikh1996** [comment]
Also, when you right click the platform sign, line 1 says "next" instead of giving a different floor value

**Comment by nixxholas** [comment]
@eirikh1996 I'll look into that soon.

Do provide me some information if you have any, or best a pull request if you have resolved it.

**Comment by eirikh1996** [comment]
I fixed it in my fork of it. Will make a pull request asap

**Comment by eirikh1996** [comment]
You still updating this or?
